In [1]:
import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 3.0.3

In [2]:
file_path = r"C:\Users\Yash 8939\OneDrive\Desktop\Digital-India-Dashboard\data\raw\digital_india.csv"

df = pd.read_csv(file_path)

df.head()

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
0,2016,2290,27,0.02,300,74.0
1,2017,2650,34,0.92,340,74.5
2,2018,2700,38,5.35,390,75.0
3,2019,2870,42,12.50,450,75.5
4,2020,2660,50,22.30,500,76.0

In [3]:
df

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
0,2016,2290,27,0.02,300,74.0
1,2017,2650,34,0.92,340,74.5
2,2018,2700,38,5.35,390,75.0
3,2019,2870,42,12.50,450,75.5
4,2020,2660,50,22.30,500,76.0
5,2021,3170,55,39.10,600,76.4
6,2022,3380,60,74.00,700,77.0
7,2023,3560,65,118.00,780,77.5
8,2024,3900,70,140.00,850,78.0
9,2025,4200,75,160.00,900,79.0

In [4]:
print("Number of Rows:", df.shape[0])
print("Number of Columns:", df.shape[1])

print("\nShape:", df.shape)

Number of Rows: 10
Number of Columns: 6

Shape: (10, 6)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                10 non-null     int64
 1   GDP_Billion         10 non-null     int64
 2   Internet_Users      10 non-null     int64
 3   UPI_Billion         10 non-null     float64
 4   Smartphone_Million  10 non-null     int64
 5   Literacy_Rate       10 non-null     float64
dtypes: float64(2), int64(4)
memory usage: 612.0 bytes

In [6]:
df.describe()

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2020.50000,3138.000000,51.600000,57.219000,581.000000,76.290000
std,3.02765,614.234845,16.132782,61.528385,217.431982,1.601007
min,2016.00000,2290.000000,27.000000,0.020000,300.000000,74.000000
25%,2018.25000,2670.000000,39.000000,7.137500,405.000000,75.125000
50%,2020.50000,3020.000000,52.500000,30.700000,550.000000,76.200000
75%,2022.75000,3515.000000,63.750000,107.000000,760.000000,77.375000
max,2025.00000,4200.000000,75.000000,160.000000,900.000000,79.000000

In [7]:
df.isnull().sum()

Year                  0
GDP_Billion           0
Internet_Users        0
UPI_Billion           0
Smartphone_Million    0
Literacy_Rate         0
dtype: int64

In [8]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [9]:
print(df.dtypes)

Year                    int64
GDP_Billion             int64
Internet_Users          int64
UPI_Billion           float64
Smartphone_Million      int64
Literacy_Rate         float64
dtype: object

In [10]:
print("Minimum GDP:", df["GDP_Billion"].min())

print("Maximum GDP:", df["GDP_Billion"].max())

print("Average GDP:", round(df["GDP_Billion"].mean(), 2))

Minimum GDP: 2290
Maximum GDP: 4200
Average GDP: 3138.0

In [11]:
print("Minimum Internet Users %:", df["Internet_Users"].min())

print("Maximum Internet Users %:", df["Internet_Users"].max())

print("Average Internet Users %:", round(df["Internet_Users"].mean(), 2))

Minimum Internet Users %: 27
Maximum Internet Users %: 75
Average Internet Users %: 51.6

In [12]:
print("Minimum Smartphone Users:", df["Smartphone_Million"].min())

print("Maximum Smartphone Users:", df["Smartphone_Million"].max())

print("Average Smartphone Users:", round(df["Smartphone_Million"].mean(), 2))

Minimum Smartphone Users: 300
Maximum Smartphone Users: 900
Average Smartphone Users: 581.0

In [13]:
print("Minimum UPI Transactions:", df["UPI_Billion"].min())

print("Maximum UPI Transactions:", df["UPI_Billion"].max())

print("Average UPI Transactions:", round(df["UPI_Billion"].mean(), 2))

Minimum UPI Transactions: 0.02
Maximum UPI Transactions: 160.0
Average UPI Transactions: 57.22

In [14]:
print("Minimum Literacy Rate:", df["Literacy_Rate"].min())

print("Maximum Literacy Rate:", df["Literacy_Rate"].max())

print("Average Literacy Rate:", round(df["Literacy_Rate"].mean(), 2))

Minimum Literacy Rate: 74.0
Maximum Literacy Rate: 79.0
Average Literacy Rate: 76.29

In [15]:
summary = pd.DataFrame({
    "Metric": [
        "GDP",
        "Internet Users",
        "UPI Transactions",
        "Smartphone Users",
        "Literacy Rate"
    ],
    "Minimum": [
        df["GDP_Billion"].min(),
        df["Internet_Users"].min(),
        df["UPI_Billion"].min(),
        df["Smartphone_Million"].min(),
        df["Literacy_Rate"].min()
    ],
    "Maximum": [
        df["GDP_Billion"].max(),
        df["Internet_Users"].max(),
        df["UPI_Billion"].max(),
        df["Smartphone_Million"].max(),
        df["Literacy_Rate"].max()
    ]
})

summary

             Metric  Minimum  Maximum
0               GDP  2290.00   4200.0
1    Internet Users    27.00     75.0
2  UPI Transactions     0.02    160.0
3  Smartphone Users   300.00    900.0
4     Literacy Rate    74.00     79.0

In [16]:
report_path = r"C:\Users\Yash 8939\OneDrive\Desktop\Digital-India-Dashboard\data\processed\collection_report.csv"

summary.to_csv(report_path, index=False)

print("Collection Report Saved Successfully!")
print(report_path)

Collection Report Saved Successfully!
C:\Users\Yash 8939\OneDrive\Desktop\Digital-India-Dashboard\data\processed\collection_report.csv

In [17]:
print("=" * 60)
print("DIGITAL INDIA DATA COLLECTION REPORT")
print("=" * 60)

print(f"Years Covered : {df['Year'].min()} - {df['Year'].max()}")

print(f"Total Records : {len(df)}")

print(f"Highest GDP : ${df['GDP_Billion'].max()} Billion")

print(f"Highest Internet Usage : {df['Internet_Users'].max()}%")

print(f"Highest Smartphone Users : {df['Smartphone_Million'].max()} Million")

print(f"Highest UPI Transactions : {df['UPI_Billion'].max()} Billion")

print(f"Highest Literacy Rate : {df['Literacy_Rate'].max()}%")

============================================================
DIGITAL INDIA DATA COLLECTION REPORT
============================================================
Years Covered : 2016 - 2025
Total Records : 10
Highest GDP : $4200 Billion
Highest Internet Usage : 75%
Highest Smartphone Users : 900 Million
Highest UPI Transactions : 160.0 Billion
Highest Literacy Rate : 79.0%