In [1]:
import pandas as pd

print("Pandas Version:", pd.__version__)

Pandas Version: 3.0.3

In [2]:
file_path = r"C:\Users\Yash 8939\OneDrive\Desktop\Digital-India-Dashboard\data\raw\digital_india.csv"

df = pd.read_csv(file_path)

df.head()

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
0,2016,2290,27,0.02,300,74.0
1,2017,2650,34,0.92,340,74.5
2,2018,2700,38,5.35,390,75.0
3,2019,2870,42,12.50,450,75.5
4,2020,2660,50,22.30,500,76.0

In [3]:
df

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
0,2016,2290,27,0.02,300,74.0
1,2017,2650,34,0.92,340,74.5
2,2018,2700,38,5.35,390,75.0
3,2019,2870,42,12.50,450,75.5
4,2020,2660,50,22.30,500,76.0
5,2021,3170,55,39.10,600,76.4
6,2022,3380,60,74.00,700,77.0
7,2023,3560,65,118.00,780,77.5
8,2024,3900,70,140.00,850,78.0
9,2025,4200,75,160.00,900,79.0

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nShape:", df.shape)

Rows: 10
Columns: 6

Shape: (10, 6)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Year                10 non-null     int64
 1   GDP_Billion         10 non-null     int64
 2   Internet_Users      10 non-null     int64
 3   UPI_Billion         10 non-null     float64
 4   Smartphone_Million  10 non-null     int64
 5   Literacy_Rate       10 non-null     float64
dtypes: float64(2), int64(4)
memory usage: 612.0 bytes

In [6]:
print("Missing Values")

df.isnull().sum()

Missing Values

Year                  0
GDP_Billion           0
Internet_Users        0
UPI_Billion           0
Smartphone_Million    0
Literacy_Rate         0
dtype: int64

In [7]:
total_missing = df.isnull().sum().sum()

print("Total Missing Values:", total_missing)

Total Missing Values: 0

In [8]:
duplicates = df.duplicated().sum()

print("Duplicate Rows:", duplicates)

Duplicate Rows: 0

In [9]:
df = df.drop_duplicates()

print("Duplicates Removed Successfully")

Duplicates Removed Successfully

In [10]:
print("Remaining Duplicates:", df.duplicated().sum())

Remaining Duplicates: 0

In [11]:
print(df.dtypes)

Year                    int64
GDP_Billion             int64
Internet_Users          int64
UPI_Billion           float64
Smartphone_Million      int64
Literacy_Rate         float64
dtype: object

In [12]:
df["Year"] = df["Year"].astype(int)

df["GDP_Billion"] = df["GDP_Billion"].astype(float)

df["Internet_Users"] = df["Internet_Users"].astype(float)

df["UPI_Billion"] = df["UPI_Billion"].astype(float)

df["Smartphone_Million"] = df["Smartphone_Million"].astype(float)

df["Literacy_Rate"] = df["Literacy_Rate"].astype(float)

print("Data Types Converted Successfully")

Data Types Converted Successfully

In [13]:
df.dtypes

Year                    int64
GDP_Billion           float64
Internet_Users        float64
UPI_Billion           float64
Smartphone_Million    float64
Literacy_Rate         float64
dtype: object

In [14]:
df.describe()

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,2020.50000,3138.000000,51.600000,57.219000,581.000000,76.290000
std,3.02765,614.234845,16.132782,61.528385,217.431982,1.601007
min,2016.00000,2290.000000,27.000000,0.020000,300.000000,74.000000
25%,2018.25000,2670.000000,39.000000,7.137500,405.000000,75.125000
50%,2020.50000,3020.000000,52.500000,30.700000,550.000000,76.200000
75%,2022.75000,3515.000000,63.750000,107.000000,760.000000,77.375000
max,2025.00000,4200.000000,75.000000,160.000000,900.000000,79.000000

In [15]:
numeric_columns = [
    "GDP_Billion",
    "Internet_Users",
    "UPI_Billion",
    "Smartphone_Million",
    "Literacy_Rate"
]

for col in numeric_columns:
    print("\n", "="*50)
    print(col)
    print("="*50)

    print("Minimum:", df[col].min())
    print("Maximum:", df[col].max())

 ==================================================
GDP_Billion
==================================================
Minimum: 2290.0
Maximum: 4200.0

 ==================================================
Internet_Users
==================================================
Minimum: 27.0
Maximum: 75.0

 ==================================================
UPI_Billion
==================================================
Minimum: 0.02
Maximum: 160.0

 ==================================================
Smartphone_Million
==================================================
Minimum: 300.0
Maximum: 900.0

 ==================================================
Literacy_Rate
==================================================
Minimum: 74.0
Maximum: 79.0

In [16]:
cleaning_report = pd.DataFrame({
    "Check": [
        "Total Rows",
        "Total Columns",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Value": [
        len(df),
        len(df.columns),
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

cleaning_report

            Check  Value
0      Total Rows     10
1   Total Columns      6
2  Missing Values      0
3  Duplicate Rows      0

In [17]:
report_path = r"C:\Users\Yash 8939\OneDrive\Desktop\Digital-India-Dashboard\data\processed\cleaning_report.csv"

cleaning_report.to_csv(
    report_path,
    index=False
)

print("Cleaning Report Saved Successfully!")

Cleaning Report Saved Successfully!

In [18]:
cleaned_path = r"C:\Users\Yash 8939\OneDrive\Desktop\Digital-India-Dashboard\data\processed\digital_india_cleaned.csv"

df.to_csv(
    cleaned_path,
    index=False
)

print("Cleaned Dataset Saved Successfully!")

Cleaned Dataset Saved Successfully!

In [19]:
verify_df = pd.read_csv(cleaned_path)

verify_df.head()

,Year,GDP_Billion,Internet_Users,UPI_Billion,Smartphone_Million,Literacy_Rate
0,2016,2290.0,27.0,0.02,300.0,74.0
1,2017,2650.0,34.0,0.92,340.0,74.5
2,2018,2700.0,38.0,5.35,390.0,75.0
3,2019,2870.0,42.0,12.50,450.0,75.5
4,2020,2660.0,50.0,22.30,500.0,76.0

In [20]:
print("=" * 60)
print("DIGITAL INDIA DATA CLEANING REPORT")
print("=" * 60)

print(f"Rows After Cleaning : {len(df)}")

print(f"Columns : {len(df.columns)}")

print(f"Missing Values : {df.isnull().sum().sum()}")

print(f"Duplicate Rows : {df.duplicated().sum()}")

print("\nDataset Successfully Cleaned and Saved")

============================================================
DIGITAL INDIA DATA CLEANING REPORT
============================================================
Rows After Cleaning : 10
Columns : 6
Missing Values : 0
Duplicate Rows : 0

Dataset Successfully Cleaned and Saved